---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.201.150.223
vector:
  hosts:
    vector-01:
      ansible_host: 51.250.35.192
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 84.252.133.224
